create DATABASE chocolate_project;
USE chocolate_project;

CREATE TABLE chocolate_sales (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date DATE,
    product VARCHAR(100),
    category VARCHAR(50),
    country VARCHAR(50),
    salesperson VARCHAR(100),
    customer VARCHAR(100),
    quantity INT,
    amount DECIMAL(10,2)
);

SELECT*
FROM chocolate_sales;

-- 1. What is the total revenue generated by the business?
SELECT SUM(amount) AS total_revenue
FROM chocolate_sales;


-- 2. What is the total quantity of products sold?
SELECT SUM(Boxes_Shipped) AS total_quantity_sold
FROM chocolate_sales;


-- 3. What is the average order value?
SELECT AVG(amount) AS avg_order_value
FROM chocolate_sales;


-- 4. How many total transactions were made?
SELECT COUNT(*) AS total_transactions
FROM chocolate_sales;


-- 5. How does revenue vary over time (monthly trend)?
SELECT 
    month,
    SUM(amount) AS monthly_revenue
FROM chocolate_sales
GROUP BY month
ORDER BY month;


-- 6. Which month generated the highest revenue?
SELECT 
    month,
    SUM(amount) AS revenue
FROM chocolate_sales
GROUP BY month
ORDER BY revenue DESC
LIMIT 5;

-- 6. Which month generated the least revenue?
SELECT 
    month,
    SUM(amount) AS revenue
FROM chocolate_sales
GROUP BY month
ORDER BY revenue ASC
LIMIT 1;


-- 7. What is the daily sales trend?
SELECT 
    date,
    SUM(amount) AS daily_revenue
FROM chocolate_sales
GROUP BY date
ORDER BY date;


-- 8. Which products generate the most revenue?
SELECT 
    product,
    SUM(amount) AS revenue
FROM chocolate_sales
GROUP BY product
ORDER BY revenue DESC;


-- 9. Which products sell the highest quantity shipping?
SELECT 
    product,
    SUM(Boxes_Shipped) AS total_quantity
FROM chocolate_sales
GROUP BY product
ORDER BY total_quantity DESC;


-- 10. Which products are the least performing (lowest revenue)?
SELECT 
    product,
    SUM(amount) AS revenue
FROM chocolate_sales
GROUP BY product
ORDER BY revenue ASC;


-- 11. Which countries generate the most revenue?
SELECT 
    country,
    SUM(amount) AS revenue
FROM chocolate_sales
GROUP BY country
ORDER BY revenue DESC;

-- 11b. Which countries generate the least revenue?
SELECT 
    country,
    SUM(amount) AS revenue
FROM chocolate_sales
GROUP BY country
ORDER BY revenue ASC;


-- 12. Which countries have the highest sales volume?
SELECT 
    country,
    SUM(Boxes_Shipped) AS total_quantity_shipped
FROM chocolate_sales
GROUP BY country
ORDER BY total_quantity_shipped DESC;


-- 13. Who are the top-performing salespersons?
SELECT 
    sales_person,
    SUM(amount) AS revenue
FROM chocolate_sales
GROUP BY sales_person
ORDER BY revenue DESC
LIMIT 10;


-- 14. What is the average sales value per salesperson?
SELECT 
    sales_person,
    AVG(amount) AS avg_sales
FROM chocolate_sales
GROUP BY sales_person;


-- 15. Which year generate the most revenue?
SELECT 
    Year,
    SUM(amount) AS revenue
FROM chocolate_sales
GROUP BY Year
ORDER BY revenue DESC;


-- 16. What is the quantity shipped sold per year?
SELECT 
    year,
    SUM(boxes_shipped) AS total_quantity
FROM chocolate_sales
GROUP BY year;


-- 17. What is the average price per product?
SELECT 
    product,
    AVG(amount / boxes_shipped) AS avg_price
FROM chocolate_sales
GROUP BY product;


-- 18. What are the top 10 highest-value transactions?
SELECT *
FROM chocolate_sales
ORDER BY amount DESC
LIMIT 10;


-- 19. Who are the top salesperson and there products by revenue?
SELECT 
    Sales_Person,
    SUM(amount) AS revenue
FROM chocolate_sales
WHERE amount>30000
GROUP BY sales_person
ORDER BY revenue DESC;



-- 20. How many sales does each salesperson make?
SELECT 
    sales_person,
    COUNT(*) AS number_of_orders
FROM chocolate_sales
GROUP BY sales_person
ORDER BY number_of_orders DESC;


-- 21. What is the Month-over-Month (MoM) revenue growth?
SELECT 
    month,
    SUM(amount) AS revenue,
    LAG(SUM(amount)) OVER (ORDER BY month) AS previous_month_revenue,
    ROUND(
        (SUM(amount) - LAG(SUM(amount)) OVER (ORDER BY month)) 
        / LAG(SUM(amount)) OVER (ORDER BY month) * 100, 2
    ) AS growth_percentage
FROM chocolate_sales
GROUP BY month
ORDER BY month;


-- 22. What is the cumulative revenue over time?
SELECT 
    month,
    SUM(amount) AS monthly_revenue,
    SUM(SUM(amount)) OVER (ORDER BY month) AS cumulative_revenue
FROM chocolate_sales
GROUP BY month
ORDER BY month;


-- 23. Which products contribute to 80% of total revenue? (Pareto Analysis)
SELECT 
    product,
    SUM(amount) AS revenue,
    SUM(SUM(amount)) OVER (ORDER BY SUM(amount) DESC) AS running_total,
    SUM(SUM(amount)) OVER () AS total_revenue,
    ROUND(
        SUM(SUM(amount)) OVER (ORDER BY SUM(amount) DESC) /
        SUM(SUM(amount)) OVER () * 100, 2
    ) AS cumulative_percentage
FROM chocolate_sales
GROUP BY product;


-- 24. What is the revenue contribution percentage of each product?
SELECT 
    product,
    SUM(amount) AS revenue,
    ROUND(
        SUM(amount) / (SELECT SUM(amount) FROM chocolate_sales) * 100, 2
    ) AS contribution_percentage
FROM chocolate_sales
GROUP BY product
ORDER BY contribution_percentage DESC;


-- 25. Which salesperson are high-value vs low-value? (sales Segmentation)
SELECT 
    sales_person,
    SUM(amount) AS total_spent,
    CASE 
        WHEN SUM(amount) > 10000 THEN 'High Value'
        WHEN SUM(amount) BETWEEN 5000 AND 10000 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS customer_segment
FROM chocolate_sales
GROUP BY sales_person
ORDER BY total_spent DESC;

-- 26. What is the average revenue per transaction by country?
SELECT 
    country,
    ROUND(SUM(amount) / COUNT(*), 2) AS avg_revenue_per_transaction
FROM chocolate_sales
GROUP BY country
ORDER BY avg_revenue_per_transaction DESC;

-- 27. Which salesperson consistently performs above average?
SELECT 
    sales_person,
    AVG(amount) AS avg_sales,
    (SELECT AVG(amount) FROM chocolate_sales) AS overall_avg,
    CASE 
        WHEN AVG(amount) > (SELECT AVG(amount) FROM chocolate_sales) 
        THEN 'Above Average'
        ELSE 'Below Average'
    END AS performance
FROM chocolate_sales
GROUP BY sales_person;

-- 28. Which products have increasing or decreasing sales trends?
SELECT 
    product,
    month,
    SUM(amount) AS revenue,
    LAG(SUM(amount)) OVER (PARTITION BY product ORDER BY month) AS prev_revenue,
    CASE 
        WHEN SUM(amount) > LAG(SUM(amount)) OVER (PARTITION BY product ORDER BY month)
        THEN 'Increasing'
        WHEN SUM(amount) < LAG(SUM(amount)) OVER (PARTITION BY product ORDER BY month)
        THEN 'Decreasing'
        ELSE 'Stable'
    END AS trend
FROM chocolate_sales
GROUP BY product, month;

-- 29. What is the top product in each country?
SELECT *
FROM (
    SELECT 
        country,
        product,
        SUM(amount) AS revenue,
        RANK() OVER (PARTITION BY country ORDER BY SUM(amount) DESC) AS rank_position
    FROM chocolate_sales
    GROUP BY country, product
) ranked
WHERE rank_position = 1;

-- 30. What is the average order size (quantity) by sales segment?
SELECT 
    sales_person,
    AVG(boxes_shipped) AS avg_quantity,
    CASE 
        WHEN AVG(boxes_shipped) > 10 THEN 'Bulk saler'
        ELSE 'Regular saler'
    END AS segment
FROM chocolate_sales
GROUP BY sales_person;

-- 31. What percentage of total revenue comes from the top 5 products?
SELECT 
    ROUND(
        SUM(revenue) / (SELECT SUM(amount) FROM chocolate_sales) * 100, 2
    ) AS top5_percentage
FROM (
    SELECT product, SUM(amount) AS revenue
    FROM chocolate_sales
    GROUP BY product
    ORDER BY revenue DESC
    LIMIT 5
) top_products;


-- 32. What is the revenue variance across months?
SELECT 
    month,
    SUM(amount) AS revenue,
    AVG(SUM(amount)) OVER () AS avg_revenue,
    SUM(amount) - AVG(SUM(amount)) OVER () AS variance
FROM chocolate_sales
GROUP BY month;

-- 33. Which countries have declining performance?
SELECT 
    country,
    month,
    SUM(amount) AS revenue,
    LAG(SUM(amount)) OVER (PARTITION BY country ORDER BY month) AS prev_revenue,
    CASE 
        WHEN SUM(amount) < LAG(SUM(amount)) OVER (PARTITION BY country ORDER BY month)
        THEN 'Declining'
        ELSE 'Growing/Stable'
    END AS performance_trend
FROM chocolate_sales
GROUP BY country, month;

-- 34. What is the revenue per unit (pricing efficiency)?
SELECT 
    product,
    SUM(amount) / SUM(boxes_shipped) AS revenue_per_unit
FROM chocolate_sales
GROUP BY product
ORDER BY revenue_per_unit DESC;




