-- Retrieve all rows and columns from the imported CSV dataset
SELECT *
FROM business_analytics_dataset;

-- Count total number of records in the dataset
SELECT COUNT(*) AS Total_Rows
FROM business_analytics_dataset;

-- View the first 20 rows to understand the dataset
SELECT *
FROM business_analytics_dataset
LIMIT 1000;

-- Detect rows with missing revenue values
SELECT *
FROM business_analytics_dataset
WHERE Calculated_Revenue IS NULL;

-- Find transactions where profit is negative
SELECT *
FROM business_analytics_dataset
WHERE Profit < 0;

-- Calculate total revenue generated by the business
SELECT SUM(Profit) AS Total_Profit
FROM business_analytics_dataset;

-- Calculate total revenue generated by the business
SELECT SUM(CAST(`Calculated Revenue` AS DECIMAL(18,2))) AS Total_Revenue
FROM business_analytics_dataset;

ALTER TABLE business_analytics_dataset
CHANGE `Calculated Revenue` Calculated_Revenue DECIMAL(18,2);

SELECT SUM(Calculated_Revenue) AS Total_Revenue
FROM business_analytics_dataset;

-- Calculate overall company profit margin
SELECT 
(SUM(Profit) / SUM(Calculated_Revenue)) * 100 AS Profit_Margin_Percentage
FROM business_analytics_dataset;

-- Calculate total products sold
SELECT SUM(Quantity) AS Total_Units_Sold
FROM business_analytics_dataset;

-- Calculate total count of products sold
SELECT Max(Quantity) AS Max_Units_Sold
FROM business_analytics_dataset;

-- Calculate total revenue generated by each product category
SELECT 
Product_Category,
SUM(Calculated_Revenue) AS Revenue_By_Category
FROM business_analytics_dataset
GROUP BY Product_Category
ORDER BY Revenue_By_Category DESC;

-- Calculate average profit generated by each product category
SELECT 
Product_Category,
AVG(Profit) AS Profit_By_Category
FROM business_analytics_dataset
GROUP BY Product_Category
ORDER BY Profit_By_Category DESC;

-- Calculate revenue generated by each region
SELECT 
Region,
SUM(Calculated_Revenue) AS Regional_Revenue
FROM business_analytics_dataset
GROUP BY Region
ORDER BY Regional_Revenue ASC;

-- Calculate profit generated in each region
SELECT 
Region,
SUM(Profit) AS Regional_Profit
FROM business_analytics_dataset
GROUP BY Region
ORDER BY Regional_Profit DESC;

-- Analyze revenue generated by each customer segment
SELECT 
Customer_Segment,
SUM(Calculated_Revenue) AS Segment_Revenue
FROM business_analytics_dataset
GROUP BY Customer_Segment
ORDER BY Segment_Revenue DESC;

-- Calculate revenue generated by each payment method
SELECT 
Payment_Method,
SUM(Calculated_Revenue) AS Revenue_By_Payment
FROM business_analytics_dataset
GROUP BY Payment_Method
ORDER BY Revenue_By_Payment DESC;

-- Analyze monthly revenue trends

SELECT Month, SUM(Calculated_Revenue) AS Monthly_Revenue
From business_analytics_dataset
GROUP BY Month
ORDER BY Month;

-- Find top 5 products generating the highest revenue
SELECT 
Product_Category,
SUM(Calculated_Revenue) AS Product_Revenue
FROM business_analytics_dataset
GROUP BY Product_Category
ORDER BY Product_Revenue DESC
LIMIT 5;

-- Find top 6 months generating the highest revenue
SELECT 
Month,
SUM(Calculated_Revenue) AS Product_Revenue
FROM business_analytics_dataset
GROUP BY Month
ORDER BY Month DESC
LIMIT 6;

-- Rank product categories by revenue using window function
SELECT 
Product_Category,
SUM(Calculated_Revenue) AS Revenue,
RANK() OVER (ORDER BY SUM(Calculated_Revenue) DESC) AS Revenue_Rank
FROM business_analytics_dataset
GROUP BY Product_Category;

-- Calculate cumulative revenue over time
SELECT 
Order_Date,
SUM(Calculated_Revenue) AS Daily_Revenue,
SUM(SUM(Calculated_Revenue)) OVER (ORDER BY Order_Date) AS Running_Revenue
FROM business_analytics_dataset
GROUP BY Order_Date;




